import type { Metadata } from "next";
import "./globals.css";
import { CategoryProvider } from "@/context/categoryContext";



export const metadata: Metadata = {
  title: "Nestify",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CategoryProvider>
        {children}
        </CategoryProvider>
        </body>
    </html>
  );
}
